#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fniessen" at-sign "pirilampo.org")
#+DATE:      2012-06-22
#+Time-stamp: <2013-10-22 Tue 09:22>
#+DESCRIPTION: Implement many AUCTeX key bindings for Org mode documents
#+KEYWORDS:  org mode, latex, auctex, key bindings, shortcuts, emulation
#+LANGUAGE:  en

#+PROPERTY:  eval no

* org-auctex-key-bindings

Implement many AUCTeX key bindings for Org mode documents, by giving them an
"Org equivalent" or Org-like effect.

** Download

Get the full Git repository at
https://github.com/fniessen/org-auctex-key-bindings using the following
command:

#+BEGIN_SRC sh
git clone https://github.com/fniessen/org-auctex-key-bindings.git
#+END_SRC

** Installation

- Install [[https://github.com/fniessen/org-auctex-key-bindings][org-auctex-key-bindings]]:

  #+BEGIN_SRC emacs-lisp
  ;; make sure `org-auctex-key-bindings.el' is in your `load-path'
  (add-to-list 'load-path "/path/to/org-auctex-key-bindings")

  ;; require it as normal
  (require 'org-auctex-keys)
  #+END_SRC

- Restart Emacs.

** Usage

Whenever you want to use AUCTeX key bindings inside your Org document, press
=C-+= or type:

#+begin_src emacs-lisp
M-x org-auctex-keys-minor-mode
#+end_src

You should now see =AUCKeys= in the list of minor modes, in your mode line.

Calling the same command another time (via =C-+= or
=M-x org-auctex-keys-minor-mode=) will disable the =AUCKeys= minor mode.

To get it automatically turned on in every Org buffer, add this in your Emacs
configuration file:

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-auctex-keys-minor-mode)
#+end_src

** AUCTeX keyboard shortcuts

Save time and boost your productivity in Org documents with AUCTeX keyboard
shortcuts.

*** Enabled AUCTeX shortcuts for Org mode

Currently implemented:

| Shortcut    | What it runs                               |
|-------------+--------------------------------------------|
| =C-c C-s=     | =org-auckeys-insert-heading=                 |
| =C-c C-j=     | =org-auckeys-insert-heading-respect-content= |
| =C-c C-f C-e= | =org-auckeys-font= (emphasize)               |
| =C-c C-f C-b= | =org-auckeys-font= (bold)                    |
| =C-c C-f C-t= | =org-auckeys-font= (typewriter)              |
| =C-c C-f C-i= | =org-auckeys-font= (italic)                  |
| =C-c C-e=     | =org-auckeys-environment=                    |
| =C-c C-c=     | =org-auckeys-export-dispatch=                |

As I'm not a heavy user of AUCTeX, I don't know which other AUCTeX keys are
important to be offered by this minor mode. Please tell me!

*** Disabled Org mode shortcuts

As there are conflicts between AUCTeX and Org key bindings, you'll temporarily
loose (whenever this minor mode is enabled) the standard behavior of:

| Shortcut | What it ran                    |
|----------+--------------------------------|
| =C-c C-s=  | =org-schedule=                   |
| =C-c C-j=  | =org-goto=                       |
| =C-c C-f=  | =org-forward-heading-same-level= |
| =C-c C-e=  | =org-export-dispatch=            |
| =C-c C-c=  | =org-ctrl-c-ctrl-c=              |

Though, you can easily regain them --- without leaving =org-auctex-keys= --- by
prefixing your keys with one =C-u=. That will call the standard Org command
*without* the =C-u= prefix.

In fact, it calls the standard Org command with one less =C-u= prefix; so:

- =C-u C-c C-s= calls the original =org-schedule=,
- =C-u C-u C-c C-s= calls the original =org-schedule= with *one* universal prefix
  argument,
- =C-u C-u C-u C-c C-s= calls the original =org-schedule= with *two* universal prefix
  arguments,
- and so on (provided it makes sense)

Another way to access a disabled Org mode shortcut is to disable
=org-auctex-keys= temporarily, do what you want, and re-enable it; that is, press
=C-+ C-c C-s C-+= to call the original =org-schedule=.

** License

Copyright (C) 2013 Fabrice Niessen

#  LocalWords:  Fabrice Niessen Org org AUCTeX auctex
