#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fniessen" at-sign "pirilampo.org")
#+DATE:      2012-06-22
#+DESCRIPTION: Implement many AUCTeX key bindings for Org mode documents
#+KEYWORDS:  org mode, latex, auctex, key bindings, shortcuts, emulation
#+LANGUAGE:  en

#+PROPERTY:  header-args :eval no

#+begin_quote
[!TIP]

*** Elevate your Emacs skills in Paris, Utrecht, Leuven or Valencia!
*Unlock the power of Emacs!  Join my next exclusive "Emacs Boost" course!*

Ready to /supercharge your productivity/ and become an Emacs ninja?  Look no
further!

*What you'll learn:*
- Master Emacs from the basics to advanced tricks.
- /Boost your editing efficiency/ and streamline your workflow.
- Customize Emacs to fit your unique needs.
- And much more!

*Audience:*

Open to anyone interested in Emacs, from beginners to advanced
users.

*Why choose my course?*
- Expert instructor with 26 years of Emacs experience.
- /Hands-on exercises/ to reinforce your learning.
- /Networking opportunities/ with like-minded Emacs enthusiasts.
- Personalized attention.

Don't miss this opportunity to take your Emacs skills to the next level! \\

Visit https://emacsboost.com/en/ for more information, dates and locations, and
to /reserve your seat/.
#+end_quote

* org-auctex-key-bindings [[http://opensource.org/licenses/GPL-3.0][http://img.shields.io/:license-gpl-blue.svg]] [[https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VCVAS6KPDQ4JC&lc=BE&item_number=org%2dauctex%2dkey%2dbindings&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted][https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif]]

Implement many AUCTeX key bindings for Org mode documents, by giving them an
"Org equivalent" or Org-like effect.

** Download

Get the full Git repository at
https://github.com/fniessen/org-auctex-key-bindings using the following
command:

#+BEGIN_SRC sh
git clone https://github.com/fniessen/org-auctex-key-bindings.git
#+END_SRC

** Installation

- Install [[https://github.com/fniessen/org-auctex-key-bindings][org-auctex-key-bindings]]:

  #+BEGIN_SRC emacs-lisp
  ;; make sure `org-auctex-key-bindings.el' is in your `load-path'
  (add-to-list 'load-path "/path/to/org-auctex-key-bindings")

  ;; require it as normal
  (require 'org-auctex-keys)
  #+END_SRC

- Restart Emacs.

** Usage

Whenever you want to use AUCTeX key bindings inside your Org document, press
=C-+= or type:

#+begin_src emacs-lisp
M-x org-auctex-keys-minor-mode
#+end_src

You should now see =AUCKeys= in the list of minor modes, in your mode line.

Calling the same command another time (via =C-+= or
=M-x org-auctex-keys-minor-mode=) will disable the =AUCKeys= minor mode.

To get it automatically turned on in every Org buffer, add this in your Emacs
configuration file:

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-auctex-keys-minor-mode)
#+end_src

** AUCTeX keyboard shortcuts

Save time and boost your productivity in Org documents with AUCTeX keyboard
shortcuts.

*** Enabled AUCTeX shortcuts for Org mode

Currently implemented:

| Shortcut    | What it runs                               |
|-------------+--------------------------------------------|
| =C-c C-s=     | =org-auckeys-insert-heading-respect-content= |
| =C-c C-j=     | =org-auckeys-insert-heading=                 |
| =C-c C-f C-e= | =org-auckeys-font= (emphasize)               |
| =C-c C-f C-b= | =org-auckeys-font= (bold)                    |
| =C-c C-f C-t= | =org-auckeys-font= (typewriter)              |
| =C-c C-f C-i= | =org-auckeys-font= (italic)                  |
| =C-c C-e=     | =org-auckeys-environment=                    |
| =C-c C-c=     | =org-auckeys-export-dispatch=                |

As I'm not a heavy user of AUCTeX, I don't know which other AUCTeX keys are
important to be offered by this minor mode. Please tell me!

*** Disabled Org mode shortcuts

As there are conflicts between AUCTeX and Org key bindings, you'll temporarily
loose (whenever this minor mode is enabled) the standard behavior of:

| Shortcut | What it ran                    |
|----------+--------------------------------|
| =C-c C-s=  | =org-schedule=                   |
| =C-c C-j=  | =org-goto=                       |
| =C-c C-f=  | =org-forward-heading-same-level= |
| =C-c C-e=  | =org-export-dispatch=            |
| =C-c C-c=  | =org-ctrl-c-ctrl-c=              |

Though, you can easily regain them --- without leaving =org-auctex-keys= --- by
prefixing your keys with one =C-u=. That will call the standard Org command
*without* the =C-u= prefix.

In fact, it calls the standard Org command with one less =C-u= prefix; so:

- =C-u C-c C-s= calls the original =org-schedule=,
- =C-u C-u C-c C-s= calls the original =org-schedule= with *one* universal prefix
  argument,
- =C-u C-u C-u C-c C-s= calls the original =org-schedule= with *two* universal prefix
  arguments,
- and so on (provided it makes sense)

Another way to access a disabled Org mode shortcut is to disable
=org-auctex-keys= temporarily, do what you want, and re-enable it; that is, press
=C-+ C-c C-s C-+= to call the original =org-schedule=.

** Contributing

*** Issues

Report issues and suggest features and improvements on the [[https://github.com/fniessen/org-auctex-key-bindings/issues/new][GitHub issue tracker]].

*** Patches

I love contributions!  Patches under any form are always welcome!

*** Donations

If you like the org-auctex-key-bindings project and feel it is making your life
better and easier, you can show your appreciation and help support future
development by making a [[https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VCVAS6KPDQ4JC&lc=BE&item_number=org%2dauctex%2dkey%2dbindings&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted][donation]] through PayPal.  Thank you!

Regardless of the donations, org-auctex-key-bindings will always be free both as
in beer and as in speech.

** License

Copyright (C) 2013-2021 Free Software Foundation, Inc.

Author: Fabrice Niessen \\
Keywords: auctex key bindings org-mode

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see http://www.gnu.org/licenses/.

#  LocalWords:  Fabrice Niessen Org org AUCTeX auctex
