#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fniessen" at-sign "pirilampo.org")
#+DATE:      2012-06-22
#+Time-stamp: <2013-09-27 Fri 15:52>
#+DESCRIPTION: Implement many AUCTeX key bindings for Org mode documents
#+KEYWORDS:  org mode, latex, auctex, key bindings, shortcuts, emulation
#+LANGUAGE:  en

* org-auctex-key-bindings

Implement many AUCTeX key bindings for Org mode documents.

** Download

Get the full Git repository at
https://github.com/fniessen/org-auctex-key-bindings using the following
command:

#+BEGIN_SRC sh
git clone https://github.com/fniessen/org-auctex-key-bindings.git
#+END_SRC

** Installation

- Install [[https://github.com/fniessen/org-auctex-key-bindings][org-auctex-key-bindings]]:

  #+BEGIN_SRC emacs-lisp
  ;; make sure `org-auctex-key-bindings.el' is in your `load-path'
  (add-to-list 'load-path "/path/to/org-auctex-key-bindings")

  ;; require it as normal
  (require 'org-auctex-keys)
  #+END_SRC

- Restart Emacs.

** Usage

Whenever you want to use AUCTeX key bindings inside your Org document, press:

#+begin_src emacs-lisp
M-x org-auctex-keys-minor-mode
#+end_src

You should now see =AUCKeys= in the list of minor modes, in your mode line.

Calling the same command another time will disable the =AUCKeys= minor mode.

** AUCTeX keyboard shortcuts

Save time and boost your productivity in Org documents with AUCTeX keyboard
shortcuts.

*** Enabled AUCTeX shortcuts for Org mode

Currently implemented:

| Shortcut    | What it runs                  |
|-------------+-------------------------------|
| =C-c C-s=     | =org-insert-heading=            |
| =C-c C-f C-e= | =org-auckeys-font= (emphasize)  |
| =C-c C-f C-b= | =org-auckeys-font= (bold)       |
| =C-c C-f C-t= | =org-auckeys-font= (typewriter) |
| =C-c C-f C-i= | =org-auckeys-font= (italic)     |
| =C-c C-e=     | =org-auckeys-environment=       |

As I'm not a heavy user of AUCTeX, I don't know which other AUCTeX keys are
important to be offered by this minor mode. Please tell me!

*** Disabled Org mode shortcuts

As there are conflicts between AUCTeX and Org key bindings, whenever this minor
mode is enabled, you'll temporarily loose the standard behavior of:

| Shortcut | What it ran                    |
|----------+--------------------------------|
| =C-c C-s=  | =org-schedule=                   |
| =C-c C-f=  | =org-forward-heading-same-level= |

** License

Copyright (C) 2013 Fabrice Niessen
